import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';
import { fetchProducts,fetchProductsBySearchParam } from './ProductListAPI';

const initialState = {
  products: [],
  status: 'idle',
  totalItems : 0
};


export const fetchAllProductsAsync = createAsyncThunk(
  'ProductList/fetchProducts',
  async () => {
    const response = await fetchProducts();

    return response.data;
  }
);

export const fetchProductsBySearchValueAsync = createAsyncThunk(
  'ProductList/fetchProductsBySearchParam',
  async ({filter, sort,Page}) => {
    const response = await fetchProductsBySearchParam(filter,sort,Page);
    return response.data;
  }
);





export const productSlice = createSlice({
  name: 'product',
  initialState,

  reducers: {

  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(fetchAllProductsAsync.pending, (state) => {
        state.status = 'loading';
      })
      .addCase(fetchAllProductsAsync.fulfilled, (state, action) => {
        state.status = 'idle';
        state.products = action.payload.data
        
      })
      .addCase(fetchProductsBySearchValueAsync.pending, (state) => {
        state.status = 'loading';
      
        
      })
      .addCase(fetchProductsBySearchValueAsync.fulfilled, (state, action) => {
        state.status = 'idle';
        state.products = action.payload.products
        state.totalItems = action.payload.totalItems
      })
  },
});

export const { increment,incrementByAmount } = productSlice.actions;

export const selectAllProducts = (state) => state.product.products;
export const stateofProducts = (state)=>state.product.status
export const totalNumberOfItems = (state)=>state.product.totalItems

export default productSlice.reducer;